version: '3.8'

services:
  service1:
    build:
      context: .
      dockerfile: Dockerfile

  service2:
    build:
      context: .
      dockerfile: Dockerfile

  service3:
    build:
      context: .
      dockerfile: Dockerfile

  webserver:
    image: nginx:alpine
    container_name: webserver
    ports:
      - "7070:80"
    volumes:
      - ./nginx-config:/etc/nginx/templates
    depends_on:
      - service1
      - service2
      - service3
